### ISSUE TITLE
Action fails

### ISSUE THREAD

**Issue by omarabid** [actions-rs/tarpaulin#16]
Do the checklist before filing an issue:

 * [x ] Is this related to the `actions-rs` Actions?
       If you think it's a problem related to Github Actions in general, use GitHub Community forum instead: https://github.community
 * [x ] You've read the Contributing section about bugs reporting: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#reporting-bugs
 * [? ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Description

The action now fails. From my understanding, this is due to: https://github.blog/changelog/2020-11-09-github-actions-removing-set-env-and-add-path-commands-on-november-16/

## Workflow code

```yaml
      - name: Run cargo-tarpaulin
        uses: omarabid-forks/rs-tarpaulin@v0.1
        with:
          version: '0.9.0'
          args: '-- --test-threads 1'
```
 
## Action output

```
Error: Unable to process command '::add-path::/home/runner/work/_temp/bd2f9558-f393-4d70-b2a0-49444c360a8b' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
