### ISSUE TITLE
Cannot read property 'find' of undefined (invalid version?)

### ISSUE THREAD

**Issue by DarkEld3r** [actions-rs/tarpaulin#3]
I have tried this action using the example from the readme:
```
...
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.9.0'
          args: '-- --test-threads 1'
...
```
But I get the following error:
```
##[error]Cannot read property 'find' of undefined
##[error]Node run failed with exit code 1
```
(https://github.com/DarkEld3r/os_info/pull/136/checks?check_run_id=430750555)

`version: latest` works for me. Perhaps the readme should be updated?
