### ISSUE TITLE
Provide example for coveralls in README

### ISSUE THREAD

**Issue by MarcoIeni** [actions-rs/tarpaulin#9]
## Motivation

Upload to coveralls example might be useful for someone.

## Workflow example

This is an example taken from [here](https://github.com/MarcoIeni/poke-speare/blob/b84a14445885f6f5b678e1bd4159c13b1e9da64d/.github/workflows/general.yml#L68-L77).

```yaml
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: '--ignore-tests --out Lcov'

      - name: upload to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: './lcov.info'
```
